### ISSUE TITLE
stock_shipment_schedule_report exports xls files with numbers formatted as text

### ISSUE THREAD

**Issue by dfrankland** [rfhk/cip-custom#7]
If possible we should export numbers into the Excel file formatted as a number not text. We can change the cell formatting in Excel no problem, but it would help if this change is easy to make.

**Comment by yostashiro** [comment]
@dukedylan It is already designed that way and the Excel template has been formatted as number.  However, the Excel somehow shows the data as text when exported from your server (which is not the case when exported from our development environment).  My advice to users have been that they once copy the data content to a text editor, and copy the content of the text editor and paste it back onto Excel again, the numbers should show properly.  Not a beautiful way, but users seem to be OK with it as far as I have heard.

**Comment by dukedylan** [comment]
I see. So what do you think on the server is causing this issue?

**Comment by yostashiro** [comment]
I am afraid I have no idea...
